package com.oio.english.util

/**
 * 根据话题名称生成口语引导问题。
 * 覆盖雅思 Part 1 常见话题，不在表中的自动用通用格式。
 */
object QuestionHints {

    private val hintMap = mapOf(
        "Work" to "What kind of work do you do? Do you enjoy it?",
        "Study" to "What do you study? Do you like your subject?",
        "Work/Study" to "Do you work or study? Tell me about it.",
        "Work or Study" to "Do you work or study? Tell me about it.",
        "Hometown" to "Where are you from? What's your hometown like?",
        "Home" to "Where do you live? Tell me about your home.",
        "Accommodation" to "Where do you live? What kind of place is it?",
        "Home/Accommodation" to "Tell me about your home. What do you like about it?",
        "Family" to "Tell me about your family. Do you live with them?",
        "Friends" to "Tell me about your friends. How often do you meet?",
        "Free Time" to "What do you do in your free time?",
        "Free Time/Hobbies" to "What do you do in your free time? Any hobbies?",
        "Hobbies" to "What are your hobbies? How long have you been doing them?",
        "Daily Routine" to "What's your typical daily routine?",
        "Morning Routine" to "What do you usually do in the morning?",
        "Food" to "What's your favorite food? What do you usually eat?",
        "Cooking" to "Do you cook? What can you cook?",
        "Restaurant" to "Do you like eating out? How often?",
        "Music" to "What kind of music do you like? Why?",
        "Sport" to "Do you play any sports? What's your favorite?",
        "Sports" to "Do you play any sports? What's your favorite?",
        "Reading" to "Do you like reading? What do you read?",
        "Books" to "Do you like reading books? What kind?",
        "Movies" to "Do you like watching movies? What's your favorite?",
        "Films" to "What kind of films do you enjoy?",
        "Travelling" to "Do you like travelling? Where have you been?",
        "Travel" to "Do you like travelling? Where have you been?",
        "Weather" to "What's the weather like where you live?",
        "Seasons" to "What's your favorite season? Why?",
        "Transport" to "How do you get around? Do you use public transport?",
        "Bicycle" to "Do you ride a bike? How often?",
        "Walking" to "Do you like walking? Where do you walk?",
        "Shopping" to "Do you like shopping? What do you usually buy?",
        "Clothes" to "What kind of clothes do you like to wear?",
        "Fashion" to "Are you interested in fashion? Why or why not?",
        "Pets" to "Do you have any pets? Would you like one?",
        "Animals" to "Do you like animals? What's your favorite animal?",
        "Plants" to "Do you like plants? Do you have any at home?",
        "Gardening" to "Do you like gardening? Do you grow anything?",
        "Colors" to "What's your favorite color? What color do you wear a lot?",
        "Numbers" to "Do you have a lucky number? Why?",
        "Birthdays" to "How do you celebrate birthdays in your country?",
        "Gifts" to "Do you like giving gifts? What do you usually give?",
        "Art" to "Do you like art? Are you good at drawing?",
        "Drawing" to "Do you like drawing? What do you draw?",
        "Photography" to "Do you like taking photos? What do you photograph?",
        "Social Media" to "Do you use social media? Which platform?",
        "Internet" to "How often do you use the internet? For what?",
        "Mobile Phone" to "Do you use your phone a lot? What for?",
        "Technology" to "Are you interested in technology? Why?",
        "TV" to "Do you watch TV? What shows do you like?",
        "Newspapers" to "Do you read newspapers or follow the news?",
        "Emails" to "Do you send many emails? How often?",
        "Concentration" to "Do you find it easy to concentrate? What distracts you?",
        "Patience" to "Are you a patient person? Give an example.",
        "Being Happy" to "What makes you happy? How do you stay happy?",
        "Laugh" to "Do you like to laugh? What makes you laugh?",
        "Dreams" to "Do you remember your dreams? What about?",
        "Sleep" to "How many hours do you sleep? Do you sleep well?",
        "Relax" to "How do you relax after a busy day?",
        "Borrowing" to "Do you borrow things from friends? What?",
        "Sharing" to "Do you like sharing things with others?",
        "Collecting" to "Do you collect anything? What?",
        "Memory" to "Do you have a good memory? How do you remember things?",
        "Computer" to "How often do you use a computer? What for?",
        "Writing" to "Do you like writing? What do you write?",
        "Handwriting" to "Do you prefer handwriting or typing? Why?",
        "Dictionary" to "Do you use a dictionary often? Paper or app?",
        "Map" to "Are you good at reading maps? Do you use maps often?",
        "Geography" to "Were you good at geography in school?",
        "History" to "Do you like history? What period interests you?",
        "Math" to "Did you like math at school? How is it useful?",
        "Science" to "Did you like science? What subject?",
        "Languages" to "How many languages do you speak? Which?",
        "English" to "Why are you learning English? How long have you studied?",
        "Learning English" to "Why are you learning English? What's most difficult?",
        "Teachers" to "Who was your favorite teacher? Why?",
        "School" to "Tell me about your school. Did you enjoy it?",
        "Primary School" to "What was your primary school like?",
        "High School" to "Tell me about your high school experience.",
        "University" to "What do you study at university? Why did you choose it?",
        "Future Plans" to "What are your plans for the future?",
        "Job" to "What's your job? Do you enjoy it?",
        "Career" to "What do you do for a living? What's your career goal?",
        "Weekends" to "What do you usually do on weekends?",
        "Holidays" to "How do you usually spend your holidays?",
        "Vacation" to "Where do you like to go on vacation?",
        "Festivals" to "What's your favorite festival? How do you celebrate it?",
        "Celebrations" to "How do you celebrate special occasions?",
        "Noise" to "Do you like a noisy or quiet environment? Why?",
        "Crowds" to "Do you like crowded places? How do you feel in crowds?",
        "Being Alone" to "Do you like spending time alone? What do you do?",
        "Running" to "Do you like running? How often do you run?",
        "Swimming" to "Can you swim? Do you like swimming?",
        "Health" to "How do you stay healthy? Any exercise?",
        "Exercise" to "Do you exercise regularly? What do you do?",
        "Breakfast" to "What do you usually eat for breakfast?",
        "Chocolate" to "Do you like chocolate? How often do you eat it?",
        "Tea/Coffee" to "Do you prefer tea or coffee? How do you like it?",
        "Tea" to "Do you drink tea? What kind do you like?",
        "Coffee" to "Do you drink coffee? How do you take it?",
        "Milk" to "Do you drink milk? Do you like it?",
        "Water" to "How much water do you drink a day?",
        "Fruit" to "What's your favorite fruit? How often do you eat it?",
        "Vegetables" to "Do you like vegetables? Which do you prefer?",
        "Weather" to "What kind of weather do you like? Why?",
        "Rain" to "Do you like rainy days? What do you do on rainy days?",
        "Sunny" to "Do you prefer sunny days? Why or why not?",
        "Cold Weather" to "How do you feel about cold weather?",
        "Hot Weather" to "What do you do in hot weather? Do you like it?",
        "Sky" to "Do you like looking at the sky? When?",
        "Stars" to "Do you like looking at stars? Have you seen a clear night sky?",
        "Sunrise" to "Do you like watching the sunrise? How often?",
        "Sunset" to "Do you like watching the sunset? Where?",
        "Museum" to "Do you like visiting museums? What kind?",
        "Art Gallery" to "Do you visit art galleries? What do you enjoy?",
        "Library" to "Do you like going to the library? What do you do there?",
        "Park" to "Do you like going to parks? What do you do there?",
        "Garden" to "Do you like gardens? Do you visit gardens?",
        "City" to "Do you like living in a city? What's good about it?",
        "Countryside" to "Do you like the countryside? Would you live there?",
        "Neighbors" to "Do you know your neighbors? What do you think of them?",
        "Street" to "What's your favorite street in your city? Why?",
        "Housework" to "Do you do housework? What chores do you do?",
        "Cleaning" to "Do you like cleaning? How often do you clean?",
        "Tidying Up" to "Do you keep your room tidy? How often do you organize?",
        "Shoes" to "Do you like buying shoes? What kind do you prefer?",
        "Bags" to "Do you like bags? What do you carry in your bag?",
        "Watch" to "Do you wear a watch? Why or why not?",
        "Jewelry" to "Do you like wearing jewelry? What kind?",
        "Hats" to "Do you wear hats? Why or why not?",
        "Mirrors" to "How often do you look in a mirror? Why?",
        "Keys" to "How many keys do you carry? What are they for?",
        "Pencil/Pen" to "Do you prefer pen or pencil? Why?",
        "Gifts" to "Do you like giving gifts? How do you choose them?",
        "Music" to "What kind of music do you listen to? When?",
        "Singing" to "Do you like singing? When do you sing?",
        "Dancing" to "Do you like dancing? How often?",
        "Board Games" to "Do you play board games? What games?",
        "Video Games" to "Do you play video games? What's your favorite?",
        "Outdoor Activities" to "What outdoor activities do you enjoy?",
        "Adventure" to "Do you like adventure? What's the most adventurous thing you've done?",
        "Being in a Hurry" to "Do you often rush? When do you feel in a hurry?",
        "Tiredness" to "What makes you tired? How do you recover?",
        "Lateness" to "Are you often late? How do you feel about lateness?",
        "Punctuality" to "Are you a punctual person? Is it important?",
        "Decision Making" to "How do you make decisions? Quickly or slowly?",
        "Problem Solving" to "How do you solve problems? Give an example.",
        "Teamwork" to "Do you prefer working alone or in a team?",
        "Leadership" to "Are you a leader? What kind of leader?",
        "Ambition" to "What's your biggest ambition? How will you achieve it?",
        "Success" to "What does success mean to you?",
        "Failure" to "How do you deal with failure? What did you learn?",
        "Change" to "Do you like change? How do you handle it?",
        "Risk" to "Do you like taking risks? Give an example.",
        "Advertisements" to "Do you watch ads? What do you think of them?",
        "News" to "How do you get the news? What interests you?",
        "Daily Routine" to "What's your typical daily routine from morning to night?"
    )

    /** 根据话题名生成引导问题 */
    fun forTopic(topicName: String): String {
        val key = topicName.trim().lowercase()

        // 精确匹配
        hintMap.entries.forEach { (k, v) ->
            if (k.lowercase() == key) return v
        }

        // 部分匹配：话题名包含关键词
        hintMap.entries.forEach { (k, v) ->
            if (key.contains(k.lowercase()) || k.lowercase().contains(key)) return v
        }

        // 通用兜底
        return "Tell me about \"$topicName\". What comes to mind?"
    }
}
